require(Rcpp)
require(BH)
Sys.setenv(CXX="/usr/local/bin/g++")
Sys.setenv("PKG_CXXFLAGS"="-std=c++11")
sourceCpp('ToR_init.cpp')
par = c(0.05, 2, 0.2, 0.25, -0.8)
res = as.vector(initialMoments(par))
print('0th order initial moments:')
print(res[1:21])
print('1st order initial moments:')
print(res[22:42])
print('2nd order initial moments:')
print(res[43:63])
print('3rd order initial moments:')
print(res[64:84])
write.csv(res, "init_moment.csv")

